name: Build and Deploy Service Image
on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "Name of the service"
        required: true
jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        uses: BSFishy/pip-action@v1
        with:
          requirements: vuln_images/requirements.txt
      - name: Build the image
        run: python3 build_image.py ../services/${{ github.event.inputs.service_name }}/deploy.yaml
        working-directory: "${{ github.workspace }}/vuln_images/"
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
      - name: Set owners # Otherwise git can not commit changes, see https://nvd.nist.gov/vuln/detail/cve-2022-24765
        run: chown -R $(id -u):$(id -g) .
        working-directory: "${{ github.workspace  }}"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: ansible/cloud/cloud_master/files/api_srv/do_vulnimages.json
          message: "[${{ github.event.inputs.service_name }}] New image built on ${{ github.sha }}"
          committer_name: GitHub Actions
          committer_email: actions@github.com
  
  deploy-image:
    runs-on: self-hosted
    needs: [build-image]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
           ref: main
      - name: Save private keys
        run: |-
          echo "$SSH_KEY" > ~/cloud_ssh_private_key;
          chmod 600 ~/cloud_ssh_private_key; 
          echo "$DO_DEPLOY_KEY" > "${{ github.workspace }}/ansible/cloud/cloud_master/files/api_srv/do_deploy_key";
          echo "$DO_TOKENS_PY" > "${{ github.workspace }}/ansible/cloud/cloud_master/files/api_srv/do_tokens.py";
        shell: bash
        env:
          SSH_KEY: ${{ secrets.CLOUD_SSH_PRIVATE_KEY }}
          DO_DEPLOY_KEY: ${{ secrets.DO_DEPLOY_KEY }}
          DO_TOKENS_PY: ${{ secrets.DO_TOKENS_PY }}
      - name: Deploy new image to the cloud
        run: ansible-playbook -vv --private-key=~/cloud_ssh_private_key cloud_master.yaml
        working-directory: "${{ github.workspace }}/ansible/cloud/"
  recreate-team-vms:
    runs-on: self-hosted
    needs: [deploy-image]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Save private key
        run: 'echo "$SSH_KEY" > ~/cloud_ssh_private_key; chmod 600 ~/cloud_ssh_private_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.CLOUD_SSH_PRIVATE_KEY }}
      - name: Copy script 
        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/cloud_ssh_private_key .github/scripts/recreate_team_vms.sh root@cloud.ctf.hitb.org:~/
      - name: Recreate team VMs
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/cloud_ssh_private_key root@cloud.ctf.hitb.org '~/recreate_team_vms.sh ${{ github.event.inputs.service_name }}'
  deploy-proxies:
    runs-on: self-hosted
    needs: [deploy-image]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        uses: BSFishy/pip-action@v1
        with:
          requirements: vuln_images/requirements.txt
      - name: Save private key
        run: |-
          echo "$DO_DEPLOY_KEY" > "${{ github.workspace }}/ansible/cloud/cloud_master/files/api_srv/do_deploy_key";
        shell: bash
        env:
          DO_DEPLOY_KEY: ${{ secrets.DO_DEPLOY_KEY }}
      - name: Deploy proxies
        run: python3 deploy_proxies.py --skip-preparation --skip-dns ../services/${{ github.event.inputs.service_name }}/deploy.yaml
        working-directory: "${{ github.workspace }}/vuln_images/"
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          CERTIFICATES_FOLDER: /etc/letsencrypt/live
          PROXY_SSH_KEY: "${{ github.workspace }}/ansible/cloud/cloud_master/files/api_srv/do_deploy_key"
          TEAMS_COUNT: 1

